export const SORT_LOW = 'SORT_LOW';
export const SORT_HIGH = 'SORT_HIGH';
export const SORT_RANGE = 'SORT_RANGE';
export const VEHICLES_LOADING_REQUEST = 'VEHICLES_LOADING_REQUEST';
export const VEHICLES_LOADING_SUCCESS = 'VEHICLES_LOADING_SUCCESS';
export const VEHICLES_LOADING_FAIL = 'VEHICLES_LOADING_FAIL';